export const LOAD_ARTICLES = 'LOAD_ARTICLES';
export const LOAD_ARTICLES_SUCCESS = 'LOAD_ARTICLES_SUCCESS';
export const LOAD_ARTICLES_FAIL = 'LOAD_ARTICLES_FAIL';

export const CHANGE_PAGINATION = 'CHANGE_PAGINATION';

export const TOGGLE_ARTICLES_LOADER = 'SHOW_ARTICLES_LOADER';