export const LOAD_ARTICLES = 'LOAD_ARTICLES';
export const LOAD_ARTICLES_SUCCESS = 'LOAD_ARTICLES_SUCCESS';
export const LOAD_ARTICLES_FAIL = 'LOAD_ARTICLES_FAIL';

export const LOAD_COMMENTS = 'LOAD_COMMENTS';
export const LOAD_COMMENTS_SUCCESS = 'LOAD_COMMENTS_SUCCESS';
export const LOAD_COMMENTS_FAIL = 'LOAD_COMMENTSS_FAIL';

export const LOAD_REPLIES = 'LOAD_REPLIES';
export const LOAD_REPLIES_SUCCESS = 'LOAD_REPLIES_SUCCESS';
export const LOAD_REPLIES_FAIL = 'LOAD_REPLIES_FAIL';

export const ADD_COMMENT = 'ADD_COMMENT';
export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS';
export const ADD_COMMENT_FAIL = 'ADD_COMMENT_FAIL';

export const CHANGE_PAGINATION = 'CHANGE_PAGINATION';

export const TOGGLE_ARTICLES_LOADER = 'SHOW_ARTICLES_LOADER';